---
- hosts: nexmon_builder
  become: yes
  vars_files:
    - external_resources.yml
  vars:
    - nexmon_interface: wlan0
  tasks:
    - name:  Review vars rpi_source
      debug: 
        var: RPI_SOURCE_FILE
    - name: Install package dependencies
      apt: 
        pkg: 
          - automake 
          - bc
          - bison
          - flex
          - gawk
          - git
          - libgmp3-dev
          - libncurses5-dev
          - libssl-dev
          - libtool-bin
          - make 
          - python2
          - qpdf
          - raspberrypi-kernel-headers
          - tcpdump
          - texinfo
        state: present
    - name: Clean the cache.
      apt:
        autoclean: yes
    - name: Copy rpi-source to node.
      copy:
        src: "{{ RPI_SOURCE_FILE }}"
        dest: /usr/local/bin/rpi-source
        owner: root
        group: root
        mode: 0655
    - name: Run rpi-source when necessary.
      command: /usr/local/bin/rpi-source -q --tag-update
      args:
        chdir: /home/pi
        creates: /home/pi/.rpi-source
    - name: Make directory for building nexmon_csi
      file:
        path: /home/pi/work/src
        owner: pi
        group: pi
        state: directory
    - name: Install the nexmon_builder scripts.
      git:
        repo: git@github.com:DuncanFyfe/nexmon_builder.git 
        dest: /home/pi/work/src/nexmon_builder
      become: no
    - name: Fix nexmon_builder install script permissions
      file: path=/home/pi/work/src/nexmon_builder/install.sh owner=pi group=pi mode=0755 state=file
    - name: DHCPC and wpasupplicant must ignore the interface used by nexmon.
      lineinfile:
        create: true
        line: "denyinterfaces {{ nexmon_interface }}"
        mode: 0664
        path: /etc/dhcpcd.conf
        state: present
      
