---
- hosts: all_raspios
  become: yes
  vars_files:
          - external_resources.yml
  tasks:
          - debug: 
                var: PI_GITHUB_ID_FILE
          - debug: 
                var: PI_GITHUB_ID_PUB_FILE
          - debug: 
                var: GITHUB_SSH_FINGERPRINT_FILE
          - debug: 
                var: SSH_CONFIG_FILE
          - name: Install always needed packages
            apt: 
                pkg: 
                        - git
                        - neovim
                        - rsync
                state: present
          - name: Clean the package caches
            apt:
                    autoclean: yes
          - name: Copy private ssh key
            copy:
                  src: "{{ PI_GITHUB_ID_FILE }}"
                  dest: /home/pi/.ssh/github_id
                  owner: pi
                  group: pi
                  mode: 0600
          - name: Copy public private ssh key
            copy:
                  src: "{{ PI_GITHUB_ID_PUB_FILE }}"
                  dest: /home/pi/.ssh/github_id.pub
                  owner: pi
                  group: pi
                  mode: 0600
          - name: Make the Github SSH fingerprint availaibe to all users
          - lineinfile:
                  create: true
                  line: "{{ lookup('file', GITHUB_SSH_FINGERPRINT_FILE) }}"
                  mode: 0644
                  path: /etc/ssh/ssh_known_hosts
                  state: present
          - name: Make the Github SSH keys the default for Github actions.
          - blockinfile:
                  create: true
                  group: pi
                  line: "{{ lookup('file', SSH_CONFIG_FILE) }}"
                  mode: 0644
                  owner: pi
                  path: /home/pi/.ssh/config
                  state: present
